stephenyeargin/hubot-grafana

src/grafana.coffee

In https://github.com/grafana/grafana/commit/e5c11691203fe68958e66693e429f6f5a3c77200 the endpoint used to get information about a dashboard has been refactored, meaning the `model` field has been renamed to `dashboard`. This commit should make sure both versions are supported.

Add support for Grafana 2.0.2+ which refactors the endpoint used

---

README.md
src/grafana.coffee
test/grafana-test.coffee

As promised.
I have implemented as I mentioned in #7 by splitting everything following the `slug:pid` part of the command depending on if there's a `=` in the word or not. All words which contain an `=` are added to the parameters list with `var-` prepended, and the ones not containing a `=` are assigned to the "from" and "to" fields in order, until they both are assigned. The rest is just discarded.
There's no URL encoding of the variables currently. I don't necessarily think that's a big problem, since stuff like spaces never should occur in a Graphite query, I would think.

Add support for templated dashboards

---

src/grafana.coffee

When calling `msg.send` multiple times, the async nature of Node.js may mean the messages comes out in another order than anticipated. This fixes that by building up one long string and sending that as one message.

Ensure list command output is in order

---

src/grafana.coffee
test/grafana-test.coffee

- Adds the `graf list` command to the help text (useful for users of `hubot-help` package)
- Handles an API discrepency on the `/search` route returning a 'result.dashboards` attribute on certain versions
/cc @Tenzer

[Patch] Fix help text, handle dashboard list issue

---

README.md
src/grafana.coffee

This is an addition to #15 and adds support for specifying the region where the S3 bucket is created, but defaults to "us-standard" which is the [default setting](https://github.com/Automattic/knox#region) in Knox.
The URL printed with Hubot is different depending on the region, so we should instead use Knox's function to get the URL of the image we have just uploaded.

Add support for using other regions than US

---

README.md
src/grafana.coffee

Some times it can be difficult to remember what number the panel was you wanted to get, but the title of the panel is likely much easier to remember, so let's use that.
This ie. adds support for doing commands such as `hubot graf db graphite-carbon-metrics:created` if you want the graph of metrics created in Carbon.
The title matching is case insensitive and just requires the search pattern to be somewhere in the title. It can currently only handle one word since the regex for the `graf db` command doesn't include spaces for the dashboard name, but I think that's okay.

Specify part of panel titles you want to see

---

src/grafana.coffee

Going by panel ID doesn't work if a panel has been moved around the dashboard after it has been created. We should instead count how many we have seen and show the correct one when we see it (if we only are to show one panel).

Count the panels we encounter to make sure we get the right panel

---

src/grafana.coffee

Fixes #19
Apparently this is not set on every returned value of `dashboard.template.list`, so we shouldn't depend on it when building the string iteroplation array. Skip if not set.

Check for template.current before using values

---

.gitignore
README.md
src/grafana.coffee
test/grafana-test.coffee

Related to #20
There is an API endpoint that accepts a query string to search available dashboards. Rather than re-invent the wheel, this adds two new calls to leverage that endpoint. This prevents a user from haivng to always use `hubot graf list` to get the entire list of the dashboards in order to query one of them.
- `hubot graf search <term>` will translate to `/api/search/?query=<term>` and return dashboards that have titles that match specified term
- `hubot graf list <tag>` will translate to `/api/search/?tag=<tag>` and return dashboards that match the specified tag

Feature: Dashboard search

---

src/grafana.coffee

Search does not return two matches. `matches[1]` contains the appropriate result.

fix search regex matching

---

README.md
src/grafana.coffee

The default time range is hard coded to 6 hours. We typically use a different time range by default in our graphs.
This introduces an optional environment variable `HUBOT_GRAFANA_QUERY_TIME_RANGE` to adjust this.

make time range configurable

---

README.md
src/grafana.coffee
test/grafana-test.coffee

Fixes #26.
This should allow a user to append a `panel-<id>` to lock a particular panel to its identifier rather than where it is visually on a dashboard. I updated the tests and it appears to work, but I'd appreciate some real-world testing with it before I merge it. :smile:
/cc @klynch @torkelo @Tenzer @ShonM

Allow panel retrieval by API identifier

---

README.md
src/grafana.coffee

This package has always been a bit noisy and relied on Slack's native "unfurling" of links. The `robot.adapterName` property has been exposed for a while (2014), so it is likely a safe bet to leverage some of the more advanced features of that adapter.
---
- Fixes #27 by making the changes there less needed.

Improved formatting for Slack clients

---

src/grafana.coffee

This `PR` has refactoring so it may be not accepted. The main goal is to provide flexibility when extending uploading images methods. Image upload is a key concept in this plugin. The idea is to extend or easily add new methods for uploading images to different services.
`fetchAndUpload` was removed. A dictionary of functions [`uploadTo`](https://github.com/gentunian/hubot-grafana/blob/master/src/grafana.coffee#L294) was introduced. It should be extended by adding a value into the object, then `uploadTo["myService"]` will be the function responsible of uploading a dashboard image to "myService".
All this logic is encapsulated within the [`sendDashboarChart`](https://github.com/gentunian/hubot-grafana/blob/master/src/grafana.coffee#L178). This function will …

Allow function hooks to upload dashboard images to multiple services

---

src/grafana.coffee

The default image width of 1000px is sometimes not enough but was originally hardcoded. This PR adds the ability to specify the width/height of the image when calling the dashboard

Add support for custom image sizes

---

src/grafana.coffee

BearyChat (https://bearychat.com) is a Slack alternative service. This pull request supported BearyChat just like Slack.
Please review, thanks.

supported BearyChat

---

package-lock.json
package.json

This PR updates the node modules, with two exceptions:
- `mocha` (installed: 2.1.0, latest 5.0.5) -- complains about overdefinition in callbacks in the S3 test suite
- `nock` (installed: 2.3.0, latest 9.2.3) -- untracable error when running tests, requires further debugging

Bump outdated versions of most modules

---

src/grafana.coffee

Currently shows the query string, which isn't terribly useful.

Add file title to Slack uploads

---

.release-it.json
package-lock.json
package.json

- Switches to `release-it` from `grunt-release`
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-16118
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-16119
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-16136
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-16138
- Fixes https://nvd.nist.gov/vuln/detail/CVE-2017-16129
Note: Does not address [https://nvd.nist.gov/vuln/detail/CVE-2017-16137](CVE-2017-16137) because `knox` has not been updated in quite some time. Solution there is most likely to swap out for the standard AWS library.

Fix security alerts, switches to release-it

---

.travis.yml
Gruntfile.js
package-lock.json
package.json
src/grafana.coffee

Finishes work from #83
The version of `knox` has long since been abandoned, but somebody has published a fork that has the requisite version bump to clear the security alert in [CVE-2017-16137](https://nvd.nist.gov/vuln/detail/CVE-2017-16137).
The long term plan is still to replace `knox` with the native S3 client.

Fix security alert in `npm audit`

---

README.md
src/grafana.coffee
test/per-room-configuration-test.coffee
test/static-configuration-test.coffee

Following #90 I'm proposing to add:
- a new environment variable to specify the user want to enable per room/channel configuration of the grafana endpoint
- a new command to set the configuration of the grafana host and api_ki and use robot brain to store it. 
The purpose is to be able to use a single instance of the bot within different channel, and each would have a different Grafana instance used for Grafana related queries.
It does not do / support the following:
- check if the user updating the conf is part of an "Admin" list of users allowed to do that
- support multiple Grafana backend for a single room / channel

Add option to configure Grafana Host and API key per room

---

CONTRIBUTING.md
README.md
src/grafana.coffee
test/timezone-test.coffee

Adds time zone support:
- Use `HUBOT_GRAFANA_DEFAULT_TIME_ZONE` env variable for a default time zone
- Use `tz=Europe/Amsterdam` for a specific time zone when requesting a dashboard
- If no time zone is specified, nothing is added to the `imageUrl`

Add TimeZone support (fixes #130)

---

README.md
src/grafana.coffee

Allows the bot to reply to a dashboard request in a thread instead.
Adds new configuration option:
```
HUBOT_GRAFANA_USE_THREADS=1
```
Fixes #145

Allow response in thread

---

src/grafana.js
test/grafana-rocketchat-test.js
test/grafana-s3-test.js

This fixes the problem mentioned in #154.
Think you were going for Virtual-host-style-access as mentioned in the docs: https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html#virtual-host-style-url-ex
But the region should come _after_ *s3.* (and it came before). I've changed the tests accordingly.

fix: S3 URL parameters in the wrong order causes image to break

---

src/grafana.js

The old Slack Hubot adapter is not maintained. Fortunately there is a modern forked version with support for Socket Mode.
The PR implements #156 
I'm not sure what testing can be done here, as the adapter should still behave in the same way. I'm still checking if this is locally the case.

feat: add support for @hubot-friends/hubot-slack adapter

---

.npmignore

Fixes #158 
Only files that are now in the package are:
And in the SRC dir:

Ingnore files for development

---

src/grafana.js

In the v7 release of Hubot, the `adapterName` value is now the node package used. This PR adjusts the matching logic so that v7 and earlier versions detect the right message format to use.

Adjust `adapterName` match for Hubot v7

---

.gitignore
package-lock.json
package.json
src/grafana.js

Should fix #161. Tried to keep the changes to a minimum. Did some local testing and my Grafana/Slack/S3 setup works like a charm.
Tests all work, but I'm not sure if they would have ever hit the actual request lib.
The _only_ drawback I see is that you need to add `--no-experiemental-fetch` when testing. This has to do with the _nock_ lib: https://github.com/nock/nock/issues/2397#issuecomment-1568646137

feat: swap out obsolete request package for node-fetch

---

.gitignore
.npmignore
package.json

Last week I had a security incident in which I uploaded something to NPM that should not have been uploaded. Because we had both a .gitignore AND an .npmingore file, the .gitignore was actually ignored. When reviewing the OWASP guidelines, I saw the recommendation that it is better to work with an explicit whitelist, instead of a blacklist (https://cheatsheetseries.owasp.org/cheatsheets/NPM_Security_Cheat_Sheet.html#1-avoid-publishing-secrets-to-the-npm-registry).
I've removed the .npmignore and added the files to the `files` property of the package.json. This prevents us from leaking information accidentally.

chore: implement OWASP recommendation for package

---

index.js

After inspecting the logs, I saw that the loader tries to `require` the following files:
- http.js
- grafana-client.js
These files will never contain something Hubot can work with. I've changed the way the loader works, so only the `grafana.js` file is loaded. When we want to load more files, we can add it to the `index.js`.

fix: load rights scripts

---

package-lock.json
package.json
src/grafana-client.js
src/service/GrafanaService.js

This PR fixes some problems:
- Fixes the way we construct the full URL, especially when people end the host with a `/`. The new `expandUrl` helps to create a URL that is acceptable.
- Error handling: in some cases Grafana will return an HTML page, we don't want that as part of our error object.
- When the first API call of `getUidBySlug` errors out, this can cause an infinite loop. We now break on the first problem. Also, paging was broken, so if you have +5000 dashboards, you could not get the right dashboard.

Fix various errors

---

.devcontainer/.profile
.devcontainer/Dockerfile
.devcontainer/startup.sh
src/Bot.js
src/adapters/Responder.js

This fixes #193. I've also update the dev container to the latest and greatest.

feature: add sendError to Responder
